version: '3.6'
services:
  telegraf:
    image: telegraf:1.15-alpine
    volumes:
    - ./telegraf/etc/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    depends_on:
      - influxdb
      - hivemq
    links:
      - influxdb
      - hivemq
    ports:
    - '0.0.0.0:8125:8125/udp'
    restart: always
  influxdb:
    image: influxdb:1.8.2-alpine
    env_file: config.env
    ports:
      - '0.0.0.0:8086:8086'
    volumes:
      - ./:/imports
      - influxdb_data:/var/lib/influxdb
    restart: always
  grafana:
    image: grafana/grafana:7.5.7
    depends_on:
      - influxdb
    env_file: config.env
    links:
      - influxdb
    ports:
      - '0.0.0.0:3000:3000'
    volumes:
      - ./grafana/data:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
      - ./grafana/dashboards/:/var/lib/grafana/dashboards/
    restart: always
    user: root
  hivemq:
    image: hivemq/hivemq4:4.6.2
    ports:
      - '0.0.0.0:1883:1883'
volumes:
  influxdb_data: {}
